apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-image-s2i
spec:
  params:
    - name: image-url
      type: string
    - name: builder-image
      type: string
    - name: registry-url
      type: string
    - name: registry-username
      type: string
    - name: registry-password
      type: string
    - name: app-name
      type: string
  steps:
    - name: build-image
      image: openshift/origin-cli
      script: |
        # create build config & image stream
       
        oc new-build --name=$(params.app-name) dotnet:8.0-ubi8 --binary=true
       


    # - name: push-image
    #   image: openshift/origin-cli
    #   script: |


  workspaces:
    - name: source