apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.url) --branch $(params.revision) /workspace/source
        #git clone https://github.com/openshift/ruby-hello-world.git
        #cd ruby-hello-world
        # oc start-build ruby-hello-world --from-dir="." --follow
----

  workspaces:
    - name: source