apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-dotnet
  name: app-dotnet
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # The default value is 25%.
      # maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process.
      maxUnavailable: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). 
      # maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxSurge: 20%
  replicas: 2
  selector:
    matchLabels:
      app: app-dotnet
  template:
    metadata:
      labels:
        app: app-dotnet
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      #todo: - pass project/ns and app name as argumement
        - image: image-registry.openshift-image-registry.svc:5000/mashraf-dev/app-dotnet:latest
          imagePullPolicy: "Always"
          name: app-dotnet
          ports:
            - containerPort: 8080
              protocol: TCP
