apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-dotnet
  name: app-dotnet
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: app-dotnet